name: Trigger

on:
- push
- pull_request

jobs:
  trigger_ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Trigger CI on related PRs
      uses: actions/github-script@v5
      with:
        # github-token: ${{ secrets.TRIGGER_GITHUB_PAT }}
        script: |
          const trigger = require('./.github/workflows/trigger-ci.js');
          const triggered = await trigger({ github, context, core, });
          core.info(`Triggered: ${JSON.stringify(triggered, null, 2)}`);
