name: Trigger

on:
- push

jobs:
  trigger_incoming_pull_requests:
    name: Trigger incoming PRs
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Trigger incoming PRs
      uses: actions/github-script@v5
      with:
        # github-token: ${{ secrets.TRIGGER_GITHUB_PAT }}
        script: |
          const triggerIncomingPullRequests = require('./.github/workflows/trigger-incoming-pull-requests.js');
          const triggeredPullRequests = await triggerIncomingPullRequests(
            { runName: "CI", github, context, core, }
          );
          core.info(`Triggered: ${JSON.stringify(triggeredPullRequests, null, 2)}`);
